import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const _localizedValues = {
    'en': {
      'app_name': 'SMS Services',
      'app_title': 'SMS SERVICES',
      'login_subtitle': 'Sign in to manage your property',
      'email': 'Email Address',
      'password': 'Password',
      'forgot_password': 'Forgot password?',
      'sign_in': 'Sign In',
      'remember_me': 'Remember me',
      'invalid_auth': 'Invalid email or password',
      'current_residence': 'Current Residence',
      'maintenance_request': 'Maintenance Request',
      'maintenance_request_desc':
          'Report an issue or track an existing request.',
      'upcoming_balance': 'Upcoming Balance',
      'due_in_days': 'Due in {} days',
      'recent_notifications': 'Recent Notifications',
      'mark_all_read': 'Mark all as read',
      'view_all': 'View all',
      'home': 'Home',
      'maintenance': 'Maintenance',
      'payments': 'Payment',
      'profile': 'Profile',
      'settings': 'Settings',
      'log_out': 'Log Out',
      'unit': 'Unit {}',
      'lease_expires': 'Lease expires {}',
      'maintenance_center': 'Maintenance Center',
      'maintenance_desc':
          'Submit new requests or review your past maintenance history.',
      'new_request': 'New Request',
      'history': 'Maintenance History',
      'category': 'Issue Category',
      'plumbing': 'Plumbing',
      'electrical': 'Electrical',
      'appliance': 'Appliance',
      'other': 'Other',
      'full_name': 'Full Name',
      'preferred_date': 'Preferred Repair Date',
      'req_info': 'Request Information',
      'describe_issue': 'Describe the issue in detail...',
      'attach_photos': 'Attach Photos',
      'upload_photos': 'Upload Photos',
      'max_photos': 'Max 3 photos, JPG or PNG',
      'submit_request': 'Submit Request',
      'req_success': 'Request Submitted Successfully',
      'view_request': 'View Request',
      'back_to_home': 'Back to Home',
      'assigned_tech': 'Assigned Technician',
      'timeline': 'Timeline',
      'status': 'Status',
      'pending': 'Pending',
      'in_progress': 'In Progress',
      'scheduled': 'Scheduled',
      'closed': 'Closed',
      'cancelled': 'Cancelled',
      'manage_balance': 'Manage your balance and review payment history.',
      'current_balance': 'Current Balance',
      'past_due': 'Past Due',
      'due_by': 'Due by {}',
      'late_status': '{} days late',
      'charge_breakdown': 'Breakdown of Charges',
      'total_due': 'Total Amount Due',
      'receipt': 'Submission Details',
      'txn_id': 'Transaction/Reference ID',
      'rent_period': 'Rent Period',
      'charges': 'Charges',
      'pay_method': 'Submission Method',
      'pay_date': 'Submission Date',
      'total': 'Total',
      'download_receipt': 'Download Receipt',
      'pay_now': 'Send Data',
      'confirm_payment': 'Confirm Submission',
      'payment_method_desc':
          'Select your submission method, enter transaction reference details, and upload proof.',
      'select_payment_method': 'SELECT METHOD',
      'proof_of_payment': 'PROOF OF SUBMISSION',
      'attach_payment_receipt': 'Tap to Attach Receipt Proof (JPG, PNG, PDF)',
      'send_amount': 'Send {}',
      'submission_success': 'Data Submitted Successfully!',
      'submission_failed': 'Submission failed: {}',
      'balance_charges': 'Balance & Charges',
      'payment_history': 'Submission History',
      'submission_success_desc':
          'Thank you. Your data has been submitted successfully for verification.',
      'view_transaction': 'View History',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'tomorrow': 'Tomorrow',
      'days_ago': '{} days ago',
      'in_days': 'In {} days',
      'due_today': 'Due Today',
      'insurance_coverage': 'Insurance Coverage',
      'insurance_desc':
          'Manage your renter\'s insurance policy details and ensure continuous coverage for your unit.',
      'active_policy': 'Active Policy',
      'policy_no': 'Policy #',
      'coverage_amount': 'Coverage Amount',
      'deductible': 'Deductible',
      'effective_date': 'Effective Date',
      'expiration_date': 'Expiration Date',
      'view_pdf': 'View Full Policy PDF',
      'update_policy': 'Update Policy Information',
      'provider': 'Insurance Provider',
      'policy_number': 'Policy Number',
      'upload_proof': 'Upload Proof of Insurance',
      'save_updates': 'Save Updates',
      'lease_reqs': 'Lease Requirements',
      'min_coverage': 'Minimum \$50,000 liability coverage.',
      'mgmt_listed':
          'Property Management Company must be listed as an "Interested Party".',
      'continuous_coverage':
          'Continuous coverage required for the duration of the lease.',
      'insurance_warning':
          'Failure to maintain active insurance may result in a non-compliance fee.',
      'lang_label': 'Language',
      'push_notif': 'Push Notifications',
      'email_notif': 'Email Notifications',
      'pay_notif': 'Payment Notifications',
      'maint_notif': 'Maintenance Notifications',
      'ins_alert': 'Insurance Alerts',
      'dark_mode': 'Dark Mode',
      'change_pw': 'Change Password',
      'privacy_policy': 'Privacy Policy',
      'terms': 'Terms & Conditions',
      'about': 'About SMS Services',
      'upload_success': 'File Uploaded Successfully',
      'error_loading': 'Unable to load content',
      'try_again': 'Try Again',
      'no_internet': 'No Internet Connection',
      'session_expired': 'Session Expired',
      'all': 'All',
      'unread': 'Unread',
      'general': 'General',
      'edit_profile': 'Edit Profile',
      'phone_number': 'Phone Number',
      'emergency_contact': 'Emergency Contact',
      'save_changes': 'Save Changes',
      'lease_start': 'Lease Start Date',
      'manager_welcome': 'Welcome Back, Owner',
      'manager_portal': 'SMS Services Property Management Portal',
      'pending_registrations': 'Pending Registrations',
      'awaiting_approval': '{} resident(s) are awaiting approval.',
      'review': 'Review',
      'quick_actions': 'QUICK ACTIONS',
      'properties_units': 'Properties & Units',
      'manage_buildings': 'Manage buildings',
      'new_lease': 'New Lease',
      'assign_apartments': 'Assign apartments',
      'notify_tenant': 'Notify Tenant',
      'send_announcement': 'Send announcement',
      'approvals': 'Approvals',
      'no_pending': 'No pending',
      'pending_count': '{} pending',
      'recent_maintenance_issues': 'RECENT MAINTENANCE ISSUES',
      'tenant_details': 'TENANT DETAILS',
      'lease_rent_details': 'LEASE & RENT DETAILS',
      'assigned_parking': 'ASSIGNED PARKING / GARAGE',
      'no_parking_assigned': 'No parking spaces assigned to this unit.',
      'rent_payment_history': 'RENT PAYMENT HISTORY',
      'renters_insurance_status': 'RENTER\'S INSURANCE STATUS',
      'liability_coverage': 'Liability Coverage',
      'view_proof_document': 'View Proof Document',
      'no_insurance_submitted':
          'Tenant hasn\'t submitted insurance details yet.',
      'mark_paid': 'Mark Paid',
      'monthly_rent': 'Monthly Rent',
      'security_deposit': 'Security Deposit',
      'issue_ticket_details': 'Issue Ticket Details',
      'description_of_issue': 'DESCRIPTION OF THE ISSUE',
      'attached_photos': 'ATTACHED PHOTOS',
      'ticket_actions': 'TICKET ACTIONS',
      'cancel_reject_ticket': 'Cancel / Reject Ticket',
      'maintenance_management': 'Maintenance Management',
      'send_alert_to_apartment': 'Send Alert to Apartment',
      'issue_rent_claim': 'Issue Rent Claim',
      'review_tenant_payments': 'Review Tenant Payments',
      'notifications_center': 'Notifications Center',
      'due': 'Due',
      'tenant_registration': 'Tenant Registration',
      'all_years': 'All Years',
      'all_buildings': 'All Buildings',
      'all_residents': 'All Residents',
      'all_units': 'All Units',
      'search_maintenance_hint': 'Search by unit #, resident, or title...',
      'no_matching_requests': 'No Matching Requests',
      'try_adjusting_filters': 'Try changing your search keywords or resetting filters.',
      'clear_filters': 'Clear Filters',
      'parking_limit_exceeded': 'A resident or apartment cannot have more than 2 active parking spaces.',
      'currently_assigned_parking': 'Currently Assigned Parking',
      'parking_replace_notice': 'Selecting new spaces will replace the current parking assignment (maximum 2 spaces).',
      'tenant_already_linked_title': 'Tenant Already Linked to an Apartment',
      'tenant_already_linked_desc': 'This tenant is currently occupying {}. To link them to a different apartment, you must first end their current tenancy (Move Out) from the Properties screen.',
      'tenant_already_linked_error': 'Cannot link tenant: Already occupying {}. End their current lease first.',
      'status_unassigned': 'Unassigned (Ready)',
      'status_occupying': 'Occupying {}',
      'filter_by': 'Filter By',
      'year': 'Year',
      'building': 'Building',
      'resident': 'Resident',
      'create_rent_claim_bill': 'Create Rent Claim Bill',
      'define_rent_bill_desc':
          'Define the monthly rent bill for an apartment unit. The tenant will receive a bill alert in their dashboard to submit proof of payment.',
      'target_apartment_resident': 'TARGET APARTMENT / RESIDENT',
      'rent_claim_title': 'Rent Claim Title',
      'rent_amount': 'Rent Amount (\$)',
      'payment_description': 'Payment Description',
      'payment_due_date': 'PAYMENT DUE DATE',
      'issue_rent_claim_send_bill': 'Issue Rent Claim & Send Bill',
      'error_loading_tenants': 'Error loading tenants directory',
      'hint_rent_title': 'e.g. September 2026 Rent Bill',
      'hint_rent_amount': 'e.g. 1500.00',
      'hint_rent_desc': 'e.g. Monthly rent due by first of month.',
      'setup_apartment_lease': 'Setup Apartment Lease',
      'add_unit_assign_tenant': 'Add Unit & Assign Tenant',
      'create_lease_desc':
          'Create a new apartment unit, define the monthly rent price, and select a registered tenant user to link them.',
      'select_registered_user': 'SELECT REGISTERED USER',
      'apartment_unit_number': 'Apartment Unit Number',
      'floor_number': 'Floor Number',
      'monthly_rent_label': 'Monthly Rent (\$)',
      'security_deposit_label': 'Security Deposit (\$)',
      'lease_start_date': 'LEASE START DATE',
      'lease_end_date': 'LEASE END DATE',
      'create_lease_link_tenant': 'Create Lease & Link Tenant',
      'error_loading_users': 'Error loading users',
      'hint_unit_number': 'e.g. Unit 501 / Apt 304',
      'hint_floor': 'e.g. 5',
    },
    'es': {
      'app_name': 'SMS Services',
      'app_title': 'SMS SERVICES',
      'login_subtitle': 'Inicie sesión para administrar su propiedad',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'forgot_password': '¿Olvidó su contraseña?',
      'sign_in': 'Iniciar sesión',
      'remember_me': 'Recordarme',
      'invalid_auth': 'Correo electrónico o contraseña incorrectos',
      'current_residence': 'Residencia actual',
      'maintenance_request': 'Solicitud de mantenimiento',
      'maintenance_request_desc':
          'Reportar un problema o realizar seguimiento.',
      'upcoming_balance': 'Saldo pendiente',
      'due_in_days': 'Vence en {} días',
      'recent_notifications': 'Notificaciones recientes',
      'mark_all_read': 'Marcar todo como leído',
      'view_all': 'Ver todo',
      'home': 'Inicio',
      'maintenance': 'Mantenimiento',
      'payments': 'Pago',
      'profile': 'Perfil',
      'settings': 'Ajustes',
      'log_out': 'Cerrar sesión',
      'unit': 'Unidad {}',
      'lease_expires': 'El contrato vence el {}',
      'maintenance_center': 'Centro de mantenimiento',
      'maintenance_desc': 'Envíe nuevas solicitudes o revise su historial.',
      'new_request': 'Nueva solicitud',
      'history': 'Historial de mantenimiento',
      'category': 'Categoría del problema',
      'plumbing': 'Plomería',
      'electrical': 'Electricidad',
      'appliance': 'Electrodoméstico',
      'other': 'Otro',
      'full_name': 'Nombre completo',
      'preferred_date': 'Fecha preferida de reparación',
      'req_info': 'Información de solicitud',
      'describe_issue': 'Describa el problema en detalle...',
      'attach_photos': 'Adjuntar fotos',
      'upload_photos': 'Subir fotos',
      'max_photos': 'Máximo 3 fotos, JPG o PNG',
      'submit_request': 'Enviar solicitud',
      'req_success': 'Solicitud enviada con éxito',
      'view_request': 'Ver solicitud',
      'back_to_home': 'Volver al inicio',
      'assigned_tech': 'Técnico asignado',
      'timeline': 'Línea de tiempo',
      'status': 'Estado',
      'pending': 'Pendiente',
      'in_progress': 'En progreso',
      'scheduled': 'Programado',
      'closed': 'Cerrado',
      'cancelled': 'Cancelado',
      'manage_balance': 'Administre su saldo e historial de pagos.',
      'current_balance': 'Saldo actual',
      'past_due': 'Vencido',
      'due_by': 'Vence el {}',
      'late_status': '{} días de retraso',
      'charge_breakdown': 'Desglose de cargos',
      'total_due': 'Total a pagar',
      'receipt': 'Detalles del envío',
      'txn_id': 'ID de transacción/referencia',
      'rent_period': 'Período de renta',
      'charges': 'Cargos',
      'pay_method': 'Método de envío',
      'pay_date': 'Fecha de envío',
      'total': 'Total',
      'download_receipt': 'Descargar recibo',
      'pay_now': 'Enviar datos',
      'confirm_payment': 'Confirmar envío',
      'payment_method_desc':
          'Seleccione el método de envío, ingrese los detalles de referencia de la transacción y cargue el comprobante.',
      'select_payment_method': 'SELECCIONAR MÉTODO',
      'proof_of_payment': 'COMPROBANTE DE ENVÍO',
      'attach_payment_receipt':
          'Toque para adjuntar comprobante (JPG, PNG, PDF)',
      'send_amount': 'Enviar {}',
      'submission_success': '¡Datos enviados con éxito!',
      'submission_failed': 'El envío falló: {}',
      'balance_charges': 'Saldo y cargos',
      'payment_history': 'Historial de envíos',
      'submission_success_desc':
          'Gracias. Sus datos han sido enviados con éxito para verificación.',
      'view_transaction': 'Ver historial',
      'today': 'Hoy',
      'yesterday': 'Ayer',
      'tomorrow': 'Mañana',
      'days_ago': 'hace {} días',
      'in_days': 'En {} días',
      'due_today': 'Vence hoy',
      'insurance_coverage': 'Cobertura de seguro',
      'insurance_desc':
          'Administre los detalles de su póliza de seguro de inquilino.',
      'active_policy': 'Póliza activa',
      'policy_no': 'Nº de póliza',
      'coverage_amount': 'Monto de cobertura',
      'deductible': 'Deducible',
      'effective_date': 'Fecha de vigencia',
      'expiration_date': 'Fecha de vencimiento',
      'view_pdf': 'Ver PDF completo de la póliza',
      'update_policy': 'Actualizar información de póliza',
      'provider': 'Proveedor de seguro',
      'policy_number': 'Número de póliza',
      'upload_proof': 'Subir comprobante de seguro',
      'save_updates': 'Guardar actualizaciones',
      'lease_reqs': 'Requisitos del contrato',
      'min_coverage': 'Cobertura mínima de responsabilidad de \$50,000.',
      'mgmt_listed':
          'La empresa de administración debe figurar como "Parte interesada".',
      'continuous_coverage':
          'Se requiere cobertura continua durante el contrato.',
      'insurance_warning':
          'El incumplimiento del seguro puede resultar en cargos adicionales.',
      'lang_label': 'Idioma',
      'push_notif': 'Notificaciones push',
      'email_notif': 'Notificaciones por correo',
      'pay_notif': 'Notificaciones de pago',
      'maint_notif': 'Notificaciones de mantenimiento',
      'ins_alert': 'Alertas de seguro',
      'dark_mode': 'Modo oscuro',
      'change_pw': 'Cambiar contraseña',
      'privacy_policy': 'Política de privacidad',
      'terms': 'Términos y condiciones',
      'about': 'Acerca de SMS Services',
      'upload_success': 'Archivo subido con éxito',
      'error_loading': 'No se pudo cargar el contenido',
      'try_again': 'Intentar de nuevo',
      'no_internet': 'Sin conexión a internet',
      'session_expired': 'Sesión expirada',
      'all': 'Todo',
      'unread': 'No leído',
      'general': 'General',
      'edit_profile': 'Editar perfil',
      'phone_number': 'Número de teléfono',
      'emergency_contact': 'Contacto de emergencia',
      'save_changes': 'Guardar cambios',
      'lease_start': 'Inicio de contrato',
      'manager_welcome': 'Bienvenido de nuevo, propietario',
      'manager_portal': 'Portal de gestión de propiedades de SMS Services',
      'pending_registrations': 'Registros pendientes',
      'awaiting_approval': '{} residente(s) están esperando aprobación.',
      'review': 'Revisar',
      'quick_actions': 'ACCIONES RÁPIDAS',
      'properties_units': 'Propiedades y unidades',
      'manage_buildings': 'Administrar edificios',
      'new_lease': 'Nuevo contrato',
      'assign_apartments': 'Asignar apartamentos',
      'notify_tenant': 'Notificar inquilino',
      'send_announcement': 'Enviar anuncio',
      'approvals': 'Aprobaciones',
      'no_pending': 'Sin pendientes',
      'pending_count': '{} pendiente(s)',
      'recent_maintenance_issues': 'PROBLEMAS RECIENTES DE MANTENIMIENTO',
      'tenant_details': 'DETALLES DEL INQUILINO',
      'lease_rent_details': 'DETALLES DEL CONTRATO Y ALQUILER',
      'assigned_parking': 'ESTACIONAMIENTO / GARAJE ASIGNADO',
      'no_parking_assigned': 'No hay espacios de estacionamiento asignados a esta unidad.',
      'rent_payment_history': 'HISTORIAL DE PAGO DE ALQUILER',
      'renters_insurance_status': 'ESTADO DEL SEGURO DEL INQUILINO',
      'liability_coverage': 'Cobertura de responsabilidad',
      'view_proof_document': 'Ver documento de prueba',
      'no_insurance_submitted':
          'El inquilino aún no ha enviado los detalles del seguro.',
      'mark_paid': 'Marcar como pagado',
      'monthly_rent': 'Alquiler mensual',
      'security_deposit': 'Depósito de seguridad',
      'issue_ticket_details': 'Detalles del ticket',
      'description_of_issue': 'DESCRIPCIÓN DEL PROBLEMA',
      'attached_photos': 'FOTOS ADJUNTAS',
      'ticket_actions': 'ACCIONES DE TICKET',
      'cancel_reject_ticket': 'Cancelar / rechazar ticket',
      'maintenance_management': 'Gestión de mantenimiento',
      'send_alert_to_apartment': 'Enviar alerta a apartamento',
      'issue_rent_claim': 'Emitir reclamo de alquiler',
      'review_tenant_payments': 'Revisar pagos de inquilino',
      'notifications_center': 'Centro de notificaciones',
      'due': 'Vencimiento',
      'tenant_registration': 'Registro de inquilino',
      'all_years': 'Todos los años',
      'all_buildings': 'Todos los edificios',
      'all_residents': 'Todos los residentes',
      'all_units': 'Todas las unidades',
      'search_maintenance_hint': 'Buscar por unidad, residente o título...',
      'no_matching_requests': 'No se encontraron solicitudes coincidentes',
      'try_adjusting_filters': 'Intente cambiar sus palabras clave o restablecer los filtros.',
      'clear_filters': 'Limpiar filtros',
      'parking_limit_exceeded': 'Un residente o apartamento no puede tener más de 2 espacios de estacionamiento activos.',
      'currently_assigned_parking': 'Estacionamiento asignado actualmente',
      'parking_replace_notice': 'Seleccionar nuevos espacios actualizará la asignación actual (máximo 2 espacios).',
      'tenant_already_linked_title': 'Inquilino ya vinculado a un apartamento',
      'tenant_already_linked_desc': 'Este inquilino está ocupando actualmente {}. Para vincularlo a un apartamento diferente, primero debe finalizar su contrato actual (Move Out) desde la pantalla de Propiedades.',
      'tenant_already_linked_error': 'No se puede vincular al inquilino: Ya está ocupando {}. Finalice primero su contrato actual.',
      'status_unassigned': 'Sin asignar (Listo)',
      'status_occupying': 'Ocupa {}',
      'filter_by': 'Filtrar por',
      'year': 'Año',
      'building': 'Edificio',
      'resident': 'Residente',
      'create_rent_claim_bill': 'Crear factura de alquiler',
      'define_rent_bill_desc':
          'Defina la factura de alquiler mensual para una unidad de apartamento. El inquilino recibirá una alerta de factura en su panel para enviar el comprobante de pago.',
      'target_apartment_resident': 'APARTAMENTO / RESIDENTE DESTINO',
      'rent_claim_title': 'Título de reclamo de alquiler',
      'rent_amount': 'Monto de alquiler (\$)',
      'payment_description': 'Descripción de pago',
      'payment_due_date': 'FECHA DE VENCIMIENTO DEL PAGO',
      'issue_rent_claim_send_bill':
          'Emitir reclamo de alquiler y enviar factura',
      'error_loading_tenants': 'Error al cargar el directorio de inquilinos',
      'hint_rent_title': 'p. ej. Factura de alquiler de septiembre de 2026',
      'hint_rent_amount': 'p. ej. 1500.00',
      'hint_rent_desc': 'p. ej. Alquiler mensual vencido el primero del mes.',
      'setup_apartment_lease': 'Configurar contrato de arrendamiento',
      'add_unit_assign_tenant': 'Agregar unidad y asignar inquilino',
      'create_lease_desc':
          'Cree una nueva unidad de apartamento, defina el precio del alquiler mensual y seleccione un usuario inquilino registrado para vincularlos.',
      'select_registered_user': 'SELECCIONAR USUARIO REGISTRADO',
      'apartment_unit_number': 'Número de unidad del apartamento',
      'floor_number': 'Número de piso',
      'monthly_rent_label': 'Alquiler mensual (\$)',
      'security_deposit_label': 'Depósito de seguridad (\$)',
      'lease_start_date': 'FECHA DE INICIO CONTRATO',
      'lease_end_date': 'FECHA DE FINALIZACIÓN CONTRATO',
      'create_lease_link_tenant': 'Crear contrato y vincular inquilino',
      'error_loading_users': 'Error al cargar usuarios',
      'hint_unit_number': 'p. ej. Unidad 501 / Apto 304',
      'hint_floor': 'p. ej. 5',
    },
    'ar': {
      'app_name': 'خدمات SMS',
      'app_title': 'خدمات SMS',
      'login_subtitle': 'سجل دخولك لإدارة وحدتك السكنية',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'sign_in': 'تسجيل الدخول',
      'remember_me': 'تذكرني',
      'invalid_auth': 'البريد الإلكتروني أو كلمة المرور غير صالحة',
      'current_residence': 'السكن الحالي',
      'maintenance_request': 'طلب صيانة',
      'maintenance_request_desc': 'الإبلاغ عن مشكلة أو تتبع طلب قائم.',
      'upcoming_balance': 'المستحقات القادمة',
      'due_in_days': 'يستحق خلال {} أيام',
      'recent_notifications': 'آخر الإشعارات',
      'mark_all_read': 'تحديد الكل كمقروء',
      'view_all': 'عرض الكل',
      'home': 'الرئيسية',
      'maintenance': 'الصيانة',
      'payments': 'المدفوعات',
      'profile': 'الملف الشخصي',
      'settings': 'الإعدادات',
      'log_out': 'تسجيل الخروج',
      'unit': 'شقة {}',
      'lease_expires': 'ينتهي العقد في {}',
      'maintenance_center': 'مركز الصيانة',
      'maintenance_desc': 'إرسال طلب جديد أو مراجعة سجل طلبات الصيانة السابقة.',
      'new_request': 'طلب جديد',
      'history': 'سجل الصيانة',
      'category': 'فئة المشكلة',
      'plumbing': 'سباكة',
      'electrical': 'كهرباء',
      'appliance': 'أجهزة منزلية',
      'other': 'أخرى',
      'full_name': 'الاسم بالكامل',
      'preferred_date': 'موعد الإصلاح المفضل',
      'req_info': 'معلومات الطلب',
      'describe_issue': 'يرجى وصف المشكلة بالتفصيل...',
      'attach_photos': 'إرفاق صور',
      'upload_photos': 'تحميل الصور',
      'max_photos': 'الحد الأقصى 3 صور، بصيغة JPG أو PNG',
      'submit_request': 'إرسال الطلب',
      'req_success': 'تم إرسال الطلب بنجاح',
      'view_request': 'عرض الطلب',
      'back_to_home': 'العودة للرئيسية',
      'assigned_tech': 'الفني المعين',
      'timeline': 'الخط الزمني',
      'status': 'الحالة',
      'pending': 'قيد الانتظار',
      'in_progress': 'قيد العمل',
      'scheduled': 'مجدول',
      'closed': 'مغلق',
      'cancelled': 'ملغى',
      'manage_balance': 'إدارة الرصيد ومراجعة سجل المدفوعات.',
      'current_balance': 'الرصيد الحالي',
      'past_due': 'متأخرات',
      'due_by': 'يستحق في {}',
      'late_status': 'متأخر منذ {} أيام',
      'charge_breakdown': 'تفاصيل المستحقات',
      'total_due': 'إجمالي المبلغ المطلوب',
      'receipt': 'تفاصيل الإرسال',
      'txn_id': 'معرف المعاملة/المرجع',
      'rent_period': 'فترة الإيجار',
      'charges': 'الرسوم والمستحقات',
      'pay_method': 'طريقة الإرسال',
      'pay_date': 'تاريخ الإرسال',
      'total': 'الإجمالي',
      'download_receipt': 'تحميل إيصال الإرسال',
      'pay_now': 'إرسال البيانات',
      'confirm_payment': 'تأكيد إرسال البيانات',
      'payment_method_desc':
          'اختر طريقة الإرسال، واكتب تفاصيل الحوالة/المرجع، ثم أرفق صورة الإثبات.',
      'select_payment_method': 'طريقة الإرسال',
      'proof_of_payment': 'إثبات الإرسال',
      'attach_payment_receipt': 'انقر لإرفاق صورة الإثبات (JPG, PNG, PDF)',
      'send_amount': 'إرسال {}',
      'submission_success': 'تم إرسال البيانات بنجاح!',
      'submission_failed': 'فشل الإرسال: {}',
      'balance_charges': 'الرصيد والمستحقات',
      'payment_history': 'سجل الإرسال',
      'submission_success_desc':
          'شكرًا لك. تم إرسال البيانات بنجاح وجاري التحقق منها.',
      'view_transaction': 'عرض السجل',
      'today': 'اليوم',
      'yesterday': 'أمس',
      'tomorrow': 'غداً',
      'days_ago': 'منذ {} أيام',
      'in_days': 'خلال {} أيام',
      'due_today': 'يستحق اليوم',
      'insurance_coverage': 'التغطية التأمينية',
      'insurance_desc':
          'إدارة تفاصيل وثيقة تأمين المستأجر وضمان التغطية المستمرة لوحدتك.',
      'active_policy': 'وثيقة تأمين نشطة',
      'policy_no': 'رقم الوثيقة',
      'coverage_amount': 'مبلغ التغطية',
      'deductible': 'مبلغ التحمل',
      'effective_date': 'تاريخ السريان',
      'expiration_date': 'تاريخ الانتهاء',
      'view_pdf': 'عرض ملف الوثيقة بالكامل PDF',
      'update_policy': 'تحديث بيانات التأمين',
      'provider': 'شركة التأمين',
      'policy_number': 'رقم وثيقة التأمين',
      'upload_proof': 'تحميل إثبات التأمين',
      'save_updates': 'حفظ التحديثات',
      'lease_reqs': 'شروط العقد',
      'min_coverage': 'الحد الأدنى للتغطية ضد المسؤولية 50,000 دولار.',
      'mgmt_listed': 'يجب إدراج شركة إدارة العقارات كـ "طرف مهتم".',
      'continuous_coverage':
          'التغطية التأمينية المستمرة مطلوبة طوال مدة الإيجار.',
      'insurance_warning':
          'قد يؤدي عدم الحفاظ على تأمين نشط إلى فرض رسوم مخالفة.',
      'lang_label': 'اللغة',
      'push_notif': 'الإشعارات الفورية',
      'email_notif': 'إشعارات البريد الإلكتروني',
      'pay_notif': 'إشعارات الدفع',
      'maint_notif': 'إشعارات الصيانة',
      'ins_alert': 'تنبيهات التأمين',
      'dark_mode': 'المظهر الداكن',
      'change_pw': 'تغيير كلمة المرور',
      'privacy_policy': 'سياسة الخصوصية',
      'terms': 'الشروط والأحكام',
      'about': 'حول خدمات SMS',
      'upload_success': 'تم تحميل الملف بنجاح',
      'error_loading': 'تعذر تحميل المحتوى',
      'try_again': 'إعادة المحاولة',
      'no_internet': 'لا يوجد اتصال بالإنترنت',
      'session_expired': 'انتهت صلاحية الجلسة',
      'all': 'الكل',
      'unread': 'غير مقروء',
      'general': 'عام',
      'edit_profile': 'تعديل الملف الشخصي',
      'phone_number': 'رقم الهاتف',
      'emergency_contact': 'جهة الاتصال في الطوارئ',
      'save_changes': 'حفظ التغييرات',
      'lease_start': 'بداية العقد',
      'manager_welcome': 'مرحباً بك مجدداً، المالك',
      'manager_portal': 'بوابة إدارة العقارات للخدمات القصيرة',
      'pending_registrations': 'التسجيلات المعلقة',
      'awaiting_approval': '{} من السكان بانتظار الموافقة.',
      'review': 'مراجعة',
      'quick_actions': 'إجراءات سريعة',
      'properties_units': 'العقارات والوحدات',
      'manage_buildings': 'إدارة المباني',
      'new_lease': 'عقد جديد',
      'assign_apartments': 'تسكين الشقق',
      'notify_tenant': 'إخطار المستأجر',
      'send_announcement': 'إرسال إعلان',
      'approvals': 'الموافقات',
      'no_pending': 'لا يوجد معلق',
      'pending_count': '{} قيد الانتظار',
      'recent_maintenance_issues': 'طلبات الصيانة الأخيرة',
      'tenant_details': 'تفاصيل المستأجر',
      'lease_rent_details': 'تفاصيل عقد الإيجار',
      'assigned_parking': 'المواقف المخصصة / الجراج',
      'no_parking_assigned': 'لا توجد مواقف سيارات مخصصة لهذه الوحدة.',
      'rent_payment_history': 'سجل سداد الإيجار',
      'renters_insurance_status': 'حالة تأمين المستأجر',
      'liability_coverage': 'تغطية المسؤولية المدنية',
      'view_proof_document': 'عرض وثيقة الإثبات',
      'no_insurance_submitted': 'لم يقم المستأجر بتقديم تفاصيل التأمين بعد.',
      'mark_paid': 'تسجيل كمدفوع',
      'monthly_rent': 'الإيجار الشهري',
      'security_deposit': 'مبلغ التأمين',
      'issue_ticket_details': 'تفاصيل تذكرة الصيانة',
      'description_of_issue': 'وصف المشكلة',
      'attached_photos': 'الصور المرفقة',
      'ticket_actions': 'إجراءات التذكرة',
      'cancel_reject_ticket': 'إلغاء / رفض التذكرة',
      'maintenance_management': 'إدارة الصيانة',
      'send_alert_to_apartment': 'إرسال تنبيه للشقة',
      'issue_rent_claim': 'إنشاء طلب إيجار',
      'review_tenant_payments': 'مراجعة مدفوعات الساكن',
      'notifications_center': 'مركز الإشعارات',
      'due': 'تاريخ الاستحقاق',
      'tenant_registration': 'تسجيل مستأجر جديد',
      'all_years': 'كل السنوات',
      'all_buildings': 'كل المباني',
      'all_residents': 'كل السكان',
      'all_units': 'كل الشقق',
      'search_maintenance_hint': 'البحث برقم الشقة، اسم الساكن، أو الموضوع...',
      'no_matching_requests': 'لا توجد طلبات صيانة مطابقة',
      'try_adjusting_filters': 'يرجى تجربة كلمات بحث أخرى أو إعادة ضبط التصفية.',
      'clear_filters': 'إعادة ضبط التصفية',
      'parking_limit_exceeded': 'لا يمكن تخصيص أكثر من موقفين نشطين لنفس الساكن أو الشقة.',
      'currently_assigned_parking': 'المواقف المخصصة حالياً',
      'parking_replace_notice': 'تحديد مواقف جديدة سيقوم بتحديث واستبدال التخصيص الحالي (بحد أقصى موقفين).',
      'tenant_already_linked_title': 'الساكن مسكن بالفعل في شقة أخرى',
      'tenant_already_linked_desc': 'هذا الساكن مرتبط حالياً بالشقة {}. لربطه بشقة جديدة، يجب أولاً إنهاء عقد إقامته الحالي (Move Out) من شاشة إدارة العقارات.',
      'tenant_already_linked_error': 'لا يمكن الربط: الساكن مرتبط بالفعل بالشقة {}. يرجى إنهاء عقده الحالي أولاً.',
      'status_unassigned': 'غير مسكن (جاهز للتسكين)',
      'status_occupying': 'مسكن في {}',
      'filter_by': 'تصفية حسب',
      'year': 'السنة',
      'building': 'المبنى',
      'resident': 'الساكن',
      'create_rent_claim_bill': 'إنشاء مطالبة قيمة الإيجار',
      'define_rent_bill_desc':
          'قم بتحديد فاتورة الإيجار الشهري للوحدة السكنية. سيتلقى المستأجر إخطاراً بالفاتورة في لوحة التحكم الخاصة به.',
      'target_apartment_resident': 'الشقة المستهدفة / الساكن',
      'rent_claim_title': 'عنوان مطالبة الإيجار',
      'rent_amount': 'قيمة الإيجار (\$)',
      'payment_description': 'وصف الدفعة',
      'payment_due_date': 'تاريخ استحقاق الدفع',
      'issue_rent_claim_send_bill': 'إصدار مطالبة الإيجار وإرسال الفاتورة',
      'error_loading_tenants': 'خطأ في تحميل دليل السكان',
      'hint_rent_title': 'مثال: إيجار شهر سبتمبر 2026',
      'hint_rent_amount': 'مثال: 1500.00',
      'hint_rent_desc': 'مثال: الإيجار الشهري مستحق في الأول من كل شهر.',
      'setup_apartment_lease': 'إعداد عقد إيجار شقة',
      'add_unit_assign_tenant': 'إضافة وحدة وتسكين مستأجر',
      'create_lease_desc':
          'قم بإنشاء وحدة سكنية جديدة، وتحديد سعر الإيجار الشهري، واختيار مستأجر مسجل لربطه بالوحدة.',
      'select_registered_user': 'اختر مستخدماً مسجلاً',
      'apartment_unit_number': 'رقم الوحدة السكنية',
      'floor_number': 'رقم الطابق',
      'monthly_rent_label': 'الإيجار الشهري (\$)',
      'security_deposit_label': 'مبلغ التأمين (\$)',
      'lease_start_date': 'تاريخ بدء عقد الإيجار',
      'lease_end_date': 'تاريخ انتهاء عقد الإيجار',
      'create_lease_link_tenant': 'إنشاء العقد وتسكين المستأجر',
      'error_loading_users': 'خطأ في تحميل قائمة المستخدمين',
      'hint_unit_number': 'مثال: وحدة 501 / شقة 304',
      'hint_floor': 'مثال: 5',
    },
  };

  String translate(String key, [String? arg]) {
    final lang = locale.languageCode;
    String value =
        _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
    if (arg != null) {
      value = value.replaceFirst('{}', arg);
    }
    return value;
  }

  /// Translates legacy UI copy while screens are migrated away from hard-coded
  /// English strings. English copy is used as the stable lookup key so every
  /// visible label, dialog, and message can share the same localization path.
  String text(String english, [String? arg]) {
    final value = _legacyText[locale.languageCode]?[english] ?? english;
    return arg == null ? value : value.replaceFirst('{}', arg);
  }

  static const Map<String, Map<String, String>> _legacyText = {
    'es': {
      'Registration Submitted': 'Registro enviado',
      'Your registration has been submitted successfully and is pending owner approval. You will be able to sign in once approved.':
          'Su registro se envió correctamente y está pendiente de aprobación. Podrá iniciar sesión cuando sea aprobado.',
      'OK': 'Aceptar',
      'Error: {}': 'Error: {}',
      'Email Address': 'Correo electrónico',
      'Phone Number': 'Número de teléfono',
      'Password': 'Contraseña',
      'Enter a strong password': 'Ingrese una contraseña segura',
      'Already have an account? ': '¿Ya tiene una cuenta? ',
      'New resident? ': '¿Es un nuevo residente? ',
      'Reset Password': 'Restablecer contraseña',
      'New Password': 'Nueva contraseña',
      'Confirm New Password': 'Confirmar nueva contraseña',
      'Confirm Password': 'Confirmar contraseña',
      'Password updated successfully!':
          '¡Contraseña actualizada correctamente!',
      'Checking profile approval status...':
          'Comprobando el estado de aprobación del perfil...',
      'Delete Account': 'Eliminar cuenta',
      'Cancel': 'Cancelar',
      'Delete Permanently': 'Eliminar permanentemente',
      'Account deleted successfully.': 'Cuenta eliminada correctamente.',
      'Are you sure you want to permanently delete your account? This action is irreversible and all your data will be permanently deleted.':
          '¿Seguro que desea eliminar permanentemente su cuenta? Esta acción es irreversible y todos sus datos se eliminarán.',
      'File size must be less than 5MB': 'El archivo debe pesar menos de 5 MB',
      'Please select an expiration date': 'Seleccione una fecha de vencimiento',
      'Policy information updated successfully!':
          '¡Información de la póliza actualizada correctamente!',
      'Coverage Amount (\$)': 'Monto de cobertura (\$)',
      'Policy ID': 'ID de póliza',
      'Maximum 3 photos allowed': 'Se permiten como máximo 3 fotos',
      'Please select a preferred repair date':
          'Seleccione una fecha de reparación preferida',
      'No maintenance requests yet': 'Aún no hay solicitudes de mantenimiento',
      'All Clear': 'Todo en orden',
      'Request {}': 'Solicitud {}',
      'Request Not Found': 'Solicitud no encontrada',
      'Submitted Date': 'Fecha de envío',
      'Preferred Date': 'Fecha preferida',
      'Assigned Tech': 'Técnico asignado',
      'Request Submitted': 'Solicitud enviada',
      'We have received your request.': 'Hemos recibido su solicitud.',
      'Request Reviewed': 'Solicitud revisada',
      'Our management has verified the details.':
          'La administración verificó los detalles.',
      'Technician Assigned': 'Técnico asignado',
      'A qualified contractor has been selected.':
          'Se seleccionó un técnico cualificado.',
      'Completed': 'Completado',
      'The issue has been resolved.': 'El problema ha sido resuelto.',
      'Request ticket not found.': 'No se encontró la solicitud.',
      'Error loading ticket': 'Error al cargar la solicitud',
      'No notifications found': 'No se encontraron notificaciones',
      'Insurance': 'Seguro',
      'No rent history found.': 'No se encontró historial de alquiler.',
      'Receipt not found.': 'No se encontró el recibo.',
      'Status': 'Estado',
      'Receipt PDF saved to Downloads directory.':
          'El PDF del recibo se guardó en Descargas.',
      'No Matching Payments': 'No hay pagos coincidentes',
      'Payment marked as paid successfully!': '¡Pago marcado como pagado!',
      'Error loading payments history': 'Error al cargar el historial de pagos',
      'Uploaded Receipt Attachment': 'Comprobante adjunto',
      'Verified Receipt': 'Comprobante verificado',
      'Secured Attachment Link': 'Enlace seguro del archivo',
      'Secure Card Checkout': 'Pago seguro con tarjeta',
      'Close': 'Cerrar',
      'View Receipt': 'Ver recibo',
      'Mark Paid': 'Marcar pagado',
      'Please select a target apartment resident!':
          'Seleccione un residente de destino.',
      'Please enter a valid amount!': 'Ingrese un monto válido.',
      'Rent claim issued and sent to tenant successfully!':
          '¡La reclamación de alquiler se envió correctamente!',
      'Unit': 'Unidad',
      'No tenants found to broadcast to!':
          'No se encontraron inquilinos para el envío.',
      'Please select a target tenant!': 'Seleccione un inquilino.',
      'Error loading tenants directory':
          'Error al cargar el directorio de inquilinos',
      'Subject Title': 'Asunto',
      'Please select a tenant user!': 'Seleccione un usuario inquilino.',
      'Please enter valid numeric details!': 'Ingrese datos numéricos válidos.',
      'New unit created and tenant linked successfully!':
          '¡Unidad creada e inquilino vinculado correctamente!',
      'Buildings & Units': 'Edificios y unidades',
      'Add Building Structure': 'Agregar estructura del edificio',
      'Building Name': 'Nombre del edificio',
      'Address': 'Dirección',
      'Floors Count': 'Número de pisos',
      'Apts Per Floor': 'Apartamentos por piso',
      'Please fill all fields correctly!':
          'Complete todos los campos correctamente.',
      'Create Structure': 'Crear estructura',
      'Building structure & units created successfully!':
          '¡Edificio y unidades creados correctamente!',
      'All Statuses': 'Todos los estados',
      'Occupied Only': 'Solo ocupados',
      'Vacant Only': 'Solo vacíos',
      'Assign Tenant': 'Asignar inquilino',
      'Error loading properties': 'Error al cargar propiedades',
      'Error loading units': 'Error al cargar unidades',
      'Pending Registrations': 'Registros pendientes',
      'Approve & Assign': 'Aprobar y asignar',
      'Reject': 'Rechazar',
      'Reject Registration': 'Rechazar registro',
      'Registration rejected and deleted.': 'Registro rechazado y eliminado.',
      'Error loading pending users': 'Error al cargar usuarios pendientes',
      '+ Add Lease': '+ Agregar contrato',
      'Broadcast All': 'Enviar a todos',
      'Send Direct Message': 'Enviar mensaje directo',
      'Pending Repairs': 'Reparaciones pendientes',
      'Total Revenue': 'Ingresos totales',
      'Error loading issues': 'Error al cargar incidencias',
      'Profile updated successfully!': '¡Perfil actualizado correctamente!',
      'Full Name': 'Nombre completo',
      'Floor Number': 'Número de piso',
      'Monthly Rent (\$)': 'Alquiler mensual (\$)',
      'Security Deposit (\$)': 'Depósito de seguridad (\$)',
      'All Buildings': 'Todos los edificios',
      'Invalid lease details!': '¡Datos del contrato no válidos!',
      'Request status updated to {}': 'Estado de la solicitud actualizado a {}',
      'Failed to pick avatar: {}': 'No se pudo seleccionar la foto: {}',
      'Failed to upload avatar: {}': 'No se pudo subir la foto: {}',
      'Error saving updates: {}': 'Error al guardar los cambios: {}',
      'Failed to pick document: {}': 'No se pudo seleccionar el documento: {}',
      'Error updating policy: {}': 'Error al actualizar la póliza: {}',
      'Failed to pick image: {}': 'No se pudo seleccionar la imagen: {}',
      'Error submitting request: {}': 'Error al enviar la solicitud: {}',
      'Create Resident Account': 'Crear cuenta de residente',
      'Register Account': 'Registrar cuenta',
      'Sign In': 'Iniciar sesión',
      'Approval Pending': 'Aprobación pendiente',
      'Check Status / Refresh': 'Comprobar estado / Actualizar',
      'Sign Out': 'Cerrar sesión',
      'Password Reset Done': 'Contraseña restablecida',
      'Go to Sign In': 'Ir a iniciar sesión',
      'Create New Password': 'Crear nueva contraseña',
      'Update Password': 'Actualizar contraseña',
      'Change Password': 'Cambiar contraseña',
      'Send Reset Link': 'Enviar enlace',
      'Check Your Email': 'Revise su correo',
      'Email is required': 'El correo es obligatorio',
      'Password is required': 'La contraseña es obligatoria',
      'Full name is required': 'El nombre es obligatorio',
      'Phone number is required': 'El teléfono es obligatorio',
      'Password must be at least 6 characters':
          'La contraseña debe tener al menos 6 caracteres',
      'Passwords do not match': 'Las contraseñas no coinciden',
      'Confirm password is required': 'Debe confirmar la contraseña',
      'Required': 'Obligatorio',
      'Preferences': 'Preferencias',
      'Theme & Security': 'Tema y seguridad',
      'Information': 'Información',
      'Personal Information': 'Información personal',
      'Residence details': 'Datos de residencia',
      'Unit Number': 'Número de unidad',
      'Property': 'Propiedad',
      'Active Issues': 'Incidencias activas',
      'Closed / History': 'Cerradas / Historial',
      'Back to Dashboard': 'Volver al panel',
      'Issue Description': 'Descripción del problema',
      'Apartment Unit': 'Unidad',
      'Tenant Name': 'Nombre del inquilino',
      'Preferred Visit': 'Visita preferida',
      'Mark In Progress': 'Marcar en curso',
      'Schedule Repair': 'Programar reparación',
      'Mark as Completed / Resolved': 'Marcar completada / resuelta',
      'Total Units': 'Total de unidades',
      'Occupied': 'Ocupadas',
      'Vacant': 'Vacías',
      'BUILDING': 'EDIFICIO',
      'STATUS': 'ESTADO',
      'Not provided': 'No proporcionado',
      'No Pending Registrations': 'No hay registros pendientes',
      'START DATE': 'FECHA DE INICIO',
      'END DATE': 'FECHA DE FIN',
      'Dispatch Notification': 'Enviar notificación',
      'Broadcast message to all apartments':
          'Enviar mensaje a todos los apartamentos',
      'TARGET TENANT / UNIT': 'INQUILINO / UNIDAD DESTINO',
      'ALERT CATEGORY': 'CATEGORÍA DE ALERTA',
      'MESSAGE BODY': 'MENSAJE',
      'Dispatch Notification Alert': 'Enviar alerta',
      'Loading...': 'Cargando...',
      'Error': 'Error',
      'APARTMENTS DIRECTORY': 'DIRECTORIO DE APARTAMENTOS',
      'Verification Receipt': 'Comprobante de verificación',
      'Ref Number': 'Número de referencia',
      'Amount Paid': 'Monto pagado',
      'Payment Channel': 'Canal de pago',
      'Payment Date': 'Fecha de pago',
      'Provider is required': 'El proveedor es obligatorio',
      'Coverage amount is required': 'El monto de cobertura es obligatorio',
      'Click to upload or drag and drop':
          'Haga clic para subir o arrastre el archivo',
      'No notifications yet.': 'Aún no hay notificaciones.',
      'Please enter the message details': 'Ingrese los detalles del mensaje',
      'Details are required': 'Los detalles son obligatorios',
      'Please describe the issue in at least 10 characters':
          'Describa el problema con al menos 10 caracteres',
      'Please upload your renter\'s insurance policy to comply with your lease agreement.':
          'Suba su póliza de seguro de inquilino para cumplir con el contrato.',
      'If you have recently renewed or changed your provider, please update your details below.':
          'Si renovó o cambió de proveedor, actualice sus datos a continuación.',
      'Select a vacant unit to assign this resident and set lease details.':
          'Seleccione una unidad vacía y establezca los datos del contrato.',
      'VACANT APARTMENT UNIT': 'UNIDAD VACÍA',
      'All registered tenants have been reviewed and approved.':
          'Todos los inquilinos registrados han sido revisados y aprobados.',
      'No units match your selected filters.':
          'Ninguna unidad coincide con los filtros.',
      'This occupied unit doesn\'t have an active lease record.':
          'Esta unidad ocupada no tiene un contrato activo.',
      'Your password has been reset successfully. You can now log in with your new password.':
          'Su contraseña se restableció. Ya puede iniciar sesión.',
      'Please enter your new password below.': 'Ingrese su nueva contraseña.',
      'Confirm Password is required': 'Debe confirmar la contraseña',
      'Enter your new password below. Make sure it is at least 6 characters long.':
          'Ingrese una contraseña nueva de al menos 6 caracteres.',
      'You\'re all caught up! There are no announcements or alerts in this category.':
          'Está al día. No hay anuncios ni alertas en esta categoría.',
      'Write a message and target it to a specific resident or broadcast it to everyone in the building. They will receive it in their app dashboard immediately.':
          'Escriba un mensaje para un residente o para todo el edificio. Lo recibirán inmediatamente.',
      'Enter announcement details here...':
          'Ingrese aquí los detalles del anuncio...',
      'Try adjusting your filters to find payment records.':
          'Ajuste los filtros para encontrar pagos.',
      'We couldn\'t find the requested maintenance details.':
          'No pudimos encontrar los detalles de mantenimiento.',
      'Report issues regarding plumbing, electrical, and other appliances.':
          'Informe problemas de plomería, electricidad y electrodomésticos.',
      'No active maintenance issues found.':
          'No se encontraron problemas activos.',
      'No registered tenants found.':
          'No se encontraron inquilinos registrados.',
      'No active maintenance issues! All systems running smoothly.':
          'No hay problemas activos. Todo funciona correctamente.',
      'No maintenance history records found.':
          'No se encontró historial de mantenimiento.',
      'Please provide details about the issue.':
          'Proporcione detalles del problema.',
      'This app complies with privacy regulation standards.':
          'Esta aplicación cumple las normas de privacidad.',
      'Terms & Conditions': 'Términos y condiciones',
      'Your account registration was successful. Please wait for the landlord/manager to approve your access and assign your apartment unit before signing in.':
          'Su registro fue exitoso. Espere a que el propietario apruebe el acceso y asigne su unidad antes de iniciar sesión.',
      'Register your profile to access building maintenance, payment history, rent claims, and message the landlord. Access requires owner approval.':
          'Registre su perfil para acceder a mantenimiento, pagos, reclamaciones y mensajes. Requiere aprobación del propietario.',
      'Your resident profile has been registered and is currently under review by the property landlord.\n\nOnce the landlord approves your access and links your profile to an apartment lease, you will be able to access the full features of the app.':
          'Su perfil está registrado y en revisión.\n\nCuando el propietario apruebe el acceso y lo vincule a un contrato, podrá usar todas las funciones.',
      'Enter the email address associated with your account and we\'ll send you instructions to reset your password.':
          'Ingrese el correo de su cuenta y le enviaremos instrucciones para restablecer la contraseña.',
      'Cannot approve tenant: No vacant units available. Please create a building structure first!':
          'No se puede aprobar: no hay unidades vacías. Cree primero la estructura del edificio.',
      'Floor: {}': 'Piso: {}',
      'Category: {}': 'Categoría: {}',
      'Unit: {}': 'Unidad: {}',
      'Resolved: ': 'Resuelto: ',
      'Submitted: ': 'Enviado: ',
      'Notification dispatched successfully!':
          '¡Notificación enviada correctamente!',
      'Monthly Rent Invoice': 'Factura de alquiler mensual',
      'Standard monthly apartment unit rent.':
          'Alquiler mensual estándar de la unidad.',
      'Hello, {}!': '¡Hola, {}!',
      'Approve & Assign: {}': 'Aprobar y asignar: {}',
      'Approved and assigned {} successfully!':
          '¡{} fue aprobado y asignado correctamente!',
      'We have sent password recovery instructions to {}.':
          'Hemos enviado instrucciones para recuperar la contraseña a {}.',
      'Broadcast message sent to {} apartments successfully!':
          '¡Mensaje enviado correctamente a {} apartamentos!',
      'REF: {}': 'REF.: {}',
      'Paid via: {}': 'Pagado mediante: {}',
    },
    'ar': {
      'Registration Submitted': 'تم إرسال التسجيل',
      'Your registration has been submitted successfully and is pending owner approval. You will be able to sign in once approved.':
          'تم إرسال طلب التسجيل بنجاح وهو الآن بانتظار موافقة المالك. يمكنك تسجيل الدخول بعد الموافقة.',
      'OK': 'حسنًا',
      'Error: {}': 'خطأ: {}',
      'Email Address': 'البريد الإلكتروني',
      'Phone Number': 'رقم الهاتف',
      'Password': 'كلمة المرور',
      'Enter a strong password': 'أدخل كلمة مرور قوية',
      'Already have an account? ': 'لديك حساب بالفعل؟ ',
      'New resident? ': 'مقيم جديد؟ ',
      'Reset Password': 'إعادة تعيين كلمة المرور',
      'New Password': 'كلمة المرور الجديدة',
      'Confirm New Password': 'تأكيد كلمة المرور الجديدة',
      'Confirm Password': 'تأكيد كلمة المرور',
      'Password updated successfully!': 'تم تحديث كلمة المرور بنجاح!',
      'Checking profile approval status...': 'جاري التحقق من حالة الموافقة...',
      'Delete Account': 'حذف الحساب',
      'Cancel': 'إلغاء',
      'Delete Permanently': 'حذف نهائي',
      'Account deleted successfully.': 'تم حذف الحساب بنجاح.',
      'Are you sure you want to permanently delete your account? This action is irreversible and all your data will be permanently deleted.':
          'هل أنت متأكد من حذف حسابك نهائيًا؟ لا يمكن التراجع عن هذا الإجراء وسيتم حذف جميع بياناتك.',
      'File size must be less than 5MB':
          'يجب أن يكون حجم الملف أقل من 5 ميجابايت',
      'Please select an expiration date': 'يرجى تحديد تاريخ الانتهاء',
      'Policy information updated successfully!':
          'تم تحديث بيانات الوثيقة بنجاح!',
      'Coverage Amount (\$)': 'مبلغ التغطية (\$)',
      'Policy ID': 'رقم الوثيقة',
      'Maximum 3 photos allowed': 'الحد الأقصى المسموح 3 صور',
      'Please select a preferred repair date': 'يرجى تحديد موعد الإصلاح المفضل',
      'No maintenance requests yet': 'لا توجد طلبات صيانة حتى الآن',
      'All Clear': 'كل شيء على ما يرام',
      'Request {}': 'الطلب {}',
      'Request Not Found': 'الطلب غير موجود',
      'Submitted Date': 'تاريخ الإرسال',
      'Preferred Date': 'التاريخ المفضل',
      'Assigned Tech': 'الفني المعيّن',
      'Request Submitted': 'تم إرسال الطلب',
      'We have received your request.': 'لقد استلمنا طلبك.',
      'Request Reviewed': 'تمت مراجعة الطلب',
      'Our management has verified the details.': 'تحققت الإدارة من التفاصيل.',
      'Technician Assigned': 'تم تعيين الفني',
      'A qualified contractor has been selected.': 'تم اختيار فني مؤهل.',
      'Completed': 'مكتمل',
      'The issue has been resolved.': 'تم حل المشكلة.',
      'Request ticket not found.': 'تذكرة الطلب غير موجودة.',
      'Error loading ticket': 'خطأ في تحميل التذكرة',
      'No notifications found': 'لا توجد إشعارات',
      'Insurance': 'التأمين',
      'No rent history found.': 'لا يوجد سجل إيجار.',
      'Receipt not found.': 'الإيصال غير موجود.',
      'Status': 'الحالة',
      'Receipt PDF saved to Downloads directory.':
          'تم حفظ ملف الإيصال في مجلد التنزيلات.',
      'No Matching Payments': 'لا توجد مدفوعات مطابقة',
      'Payment marked as paid successfully!': 'تم تسجيل الدفعة كمدفوعة بنجاح!',
      'Error loading payments history': 'خطأ في تحميل سجل المدفوعات',
      'Uploaded Receipt Attachment': 'مرفق إيصال الدفع',
      'Verified Receipt': 'إيصال موثق',
      'Secured Attachment Link': 'رابط المرفق الآمن',
      'Secure Card Checkout': 'دفع آمن بالبطاقة',
      'Close': 'إغلاق',
      'View Receipt': 'عرض الإيصال',
      'Mark Paid': 'تسجيل كمدفوع',
      'Please select a target apartment resident!':
          'يرجى اختيار الساكن المستهدف.',
      'Please enter a valid amount!': 'يرجى إدخال مبلغ صحيح.',
      'Rent claim issued and sent to tenant successfully!':
          'تم إصدار مطالبة الإيجار وإرسالها بنجاح!',
      'Unit': 'الوحدة',
      'No tenants found to broadcast to!':
          'لا يوجد مستأجرون لإرسال الإعلان إليهم.',
      'Please select a target tenant!': 'يرجى اختيار المستأجر المستهدف.',
      'Error loading tenants directory': 'خطأ في تحميل دليل السكان',
      'Subject Title': 'عنوان الرسالة',
      'Please select a tenant user!': 'يرجى اختيار مستخدم مستأجر.',
      'Please enter valid numeric details!': 'يرجى إدخال بيانات رقمية صحيحة.',
      'New unit created and tenant linked successfully!':
          'تم إنشاء الوحدة وربط المستأجر بنجاح!',
      'Buildings & Units': 'المباني والوحدات',
      'Add Building Structure': 'إضافة هيكل مبنى',
      'Building Name': 'اسم المبنى',
      'Address': 'العنوان',
      'Floors Count': 'عدد الطوابق',
      'Apts Per Floor': 'الشقق بكل طابق',
      'Please fill all fields correctly!': 'يرجى ملء جميع الحقول بصورة صحيحة.',
      'Create Structure': 'إنشاء الهيكل',
      'Building structure & units created successfully!':
          'تم إنشاء المبنى والوحدات بنجاح!',
      'All Statuses': 'كل الحالات',
      'Occupied Only': 'المشغولة فقط',
      'Vacant Only': 'الشاغرة فقط',
      'Assign Tenant': 'تعيين مستأجر',
      'Error loading properties': 'خطأ في تحميل العقارات',
      'Error loading units': 'خطأ في تحميل الوحدات',
      'Pending Registrations': 'التسجيلات المعلقة',
      'Approve & Assign': 'موافقة وتعيين',
      'Reject': 'رفض',
      'Reject Registration': 'رفض التسجيل',
      'Registration rejected and deleted.': 'تم رفض التسجيل وحذفه.',
      'Error loading pending users': 'خطأ في تحميل المستخدمين المعلقين',
      '+ Add Lease': '+ إضافة عقد',
      'Broadcast All': 'إرسال للجميع',
      'Send Direct Message': 'إرسال رسالة مباشرة',
      'Pending Repairs': 'الإصلاحات المعلقة',
      'Total Revenue': 'إجمالي الإيرادات',
      'Error loading issues': 'خطأ في تحميل المشكلات',
      'Profile updated successfully!': 'تم تحديث الملف الشخصي بنجاح!',
      'Full Name': 'الاسم بالكامل',
      'Floor Number': 'رقم الطابق',
      'Monthly Rent (\$)': 'الإيجار الشهري (\$)',
      'Security Deposit (\$)': 'مبلغ التأمين (\$)',
      'All Buildings': 'كل المباني',
      'Invalid lease details!': 'بيانات العقد غير صحيحة!',
      'Request status updated to {}': 'تم تحديث حالة الطلب إلى {}',
      'Failed to pick avatar: {}': 'تعذر اختيار الصورة: {}',
      'Failed to upload avatar: {}': 'تعذر رفع الصورة: {}',
      'Error saving updates: {}': 'خطأ في حفظ التحديثات: {}',
      'Failed to pick document: {}': 'تعذر اختيار المستند: {}',
      'Error updating policy: {}': 'خطأ في تحديث الوثيقة: {}',
      'Failed to pick image: {}': 'تعذر اختيار الصورة: {}',
      'Error submitting request: {}': 'خطأ في إرسال الطلب: {}',
      'Create Resident Account': 'إنشاء حساب ساكن',
      'Register Account': 'تسجيل الحساب',
      'Sign In': 'تسجيل الدخول',
      'Approval Pending': 'الموافقة معلقة',
      'Check Status / Refresh': 'التحقق من الحالة / تحديث',
      'Sign Out': 'تسجيل الخروج',
      'Password Reset Done': 'تمت إعادة تعيين كلمة المرور',
      'Go to Sign In': 'الذهاب لتسجيل الدخول',
      'Create New Password': 'إنشاء كلمة مرور جديدة',
      'Update Password': 'تحديث كلمة المرور',
      'Change Password': 'تغيير كلمة المرور',
      'Send Reset Link': 'إرسال رابط الاستعادة',
      'Check Your Email': 'راجع بريدك الإلكتروني',
      'Email is required': 'البريد الإلكتروني مطلوب',
      'Password is required': 'كلمة المرور مطلوبة',
      'Full name is required': 'الاسم بالكامل مطلوب',
      'Phone number is required': 'رقم الهاتف مطلوب',
      'Password must be at least 6 characters':
          'يجب ألا تقل كلمة المرور عن 6 أحرف',
      'Passwords do not match': 'كلمتا المرور غير متطابقتين',
      'Confirm password is required': 'تأكيد كلمة المرور مطلوب',
      'Required': 'مطلوب',
      'Preferences': 'التفضيلات',
      'Theme & Security': 'المظهر والأمان',
      'Information': 'المعلومات',
      'Personal Information': 'المعلومات الشخصية',
      'Residence details': 'تفاصيل السكن',
      'Unit Number': 'رقم الوحدة',
      'Property': 'العقار',
      'Active Issues': 'المشكلات النشطة',
      'Closed / History': 'المغلقة / السجل',
      'Back to Dashboard': 'العودة للوحة التحكم',
      'Issue Description': 'وصف المشكلة',
      'Apartment Unit': 'الوحدة السكنية',
      'Tenant Name': 'اسم المستأجر',
      'Preferred Visit': 'موعد الزيارة المفضل',
      'Mark In Progress': 'بدء العمل',
      'Schedule Repair': 'جدولة الإصلاح',
      'Mark as Completed / Resolved': 'تسجيل كمكتمل / محلول',
      'Total Units': 'إجمالي الوحدات',
      'Occupied': 'مشغولة',
      'Vacant': 'شاغرة',
      'BUILDING': 'المبنى',
      'STATUS': 'الحالة',
      'Not provided': 'غير متوفر',
      'No Pending Registrations': 'لا توجد تسجيلات معلقة',
      'START DATE': 'تاريخ البداية',
      'END DATE': 'تاريخ النهاية',
      'Dispatch Notification': 'إرسال إشعار',
      'Broadcast message to all apartments': 'إرسال رسالة إلى جميع الشقق',
      'TARGET TENANT / UNIT': 'المستأجر / الوحدة المستهدفة',
      'ALERT CATEGORY': 'فئة التنبيه',
      'MESSAGE BODY': 'نص الرسالة',
      'Dispatch Notification Alert': 'إرسال التنبيه',
      'Loading...': 'جاري التحميل...',
      'Error': 'خطأ',
      'APARTMENTS DIRECTORY': 'دليل الشقق',
      'Verification Receipt': 'إيصال التحقق',
      'Ref Number': 'رقم المرجع',
      'Amount Paid': 'المبلغ المدفوع',
      'Payment Channel': 'قناة الدفع',
      'Payment Date': 'تاريخ الدفع',
      'Provider is required': 'شركة التأمين مطلوبة',
      'Coverage amount is required': 'مبلغ التغطية مطلوب',
      'Click to upload or drag and drop': 'اضغط للرفع أو اسحب الملف وأفلته',
      'No notifications yet.': 'لا توجد إشعارات حتى الآن.',
      'Please enter the message details': 'يرجى إدخال تفاصيل الرسالة',
      'Details are required': 'التفاصيل مطلوبة',
      'Please describe the issue in at least 10 characters':
          'يرجى وصف المشكلة في 10 أحرف على الأقل',
      'Please upload your renter\'s insurance policy to comply with your lease agreement.':
          'يرجى رفع وثيقة تأمين المستأجر للالتزام بعقد الإيجار.',
      'If you have recently renewed or changed your provider, please update your details below.':
          'إذا جددت الوثيقة أو غيرت الشركة، حدّث بياناتك أدناه.',
      'Select a vacant unit to assign this resident and set lease details.':
          'اختر وحدة شاغرة لتعيين هذا الساكن وحدد تفاصيل العقد.',
      'VACANT APARTMENT UNIT': 'الوحدة السكنية الشاغرة',
      'All registered tenants have been reviewed and approved.':
          'تمت مراجعة جميع المستأجرين المسجلين والموافقة عليهم.',
      'No units match your selected filters.':
          'لا توجد وحدات تطابق عوامل التصفية.',
      'This occupied unit doesn\'t have an active lease record.':
          'لا يوجد عقد إيجار نشط لهذه الوحدة المشغولة.',
      'Your password has been reset successfully. You can now log in with your new password.':
          'تمت إعادة تعيين كلمة المرور ويمكنك تسجيل الدخول الآن.',
      'Please enter your new password below.':
          'أدخل كلمة المرور الجديدة أدناه.',
      'Confirm Password is required': 'تأكيد كلمة المرور مطلوب',
      'Enter your new password below. Make sure it is at least 6 characters long.':
          'أدخل كلمة مرور جديدة لا تقل عن 6 أحرف.',
      'You\'re all caught up! There are no announcements or alerts in this category.':
          'أنت مطّلع على كل شيء. لا توجد إعلانات أو تنبيهات في هذه الفئة.',
      'Write a message and target it to a specific resident or broadcast it to everyone in the building. They will receive it in their app dashboard immediately.':
          'اكتب رسالة لمقيم محدد أو أرسلها إلى جميع سكان المبنى وستصلهم فورًا.',
      'Enter announcement details here...': 'أدخل تفاصيل الإعلان هنا...',
      'Try adjusting your filters to find payment records.':
          'جرّب تعديل عوامل التصفية للعثور على سجلات الدفع.',
      'We couldn\'t find the requested maintenance details.':
          'تعذر العثور على تفاصيل طلب الصيانة.',
      'Report issues regarding plumbing, electrical, and other appliances.':
          'أبلغ عن مشكلات السباكة والكهرباء والأجهزة الأخرى.',
      'No active maintenance issues found.': 'لا توجد مشكلات صيانة نشطة.',
      'No registered tenants found.': 'لا يوجد مستأجرون مسجلون.',
      'No active maintenance issues! All systems running smoothly.':
          'لا توجد مشكلات صيانة نشطة، وكل الأنظمة تعمل جيدًا.',
      'No maintenance history records found.': 'لا توجد سجلات صيانة سابقة.',
      'Please provide details about the issue.': 'يرجى تقديم تفاصيل المشكلة.',
      'This app complies with privacy regulation standards.':
          'يتوافق هذا التطبيق مع معايير حماية الخصوصية.',
      'Terms & Conditions': 'الشروط والأحكام',
      'Your account registration was successful. Please wait for the landlord/manager to approve your access and assign your apartment unit before signing in.':
          'تم تسجيل حسابك بنجاح. انتظر موافقة المالك وتعيين وحدتك قبل تسجيل الدخول.',
      'Register your profile to access building maintenance, payment history, rent claims, and message the landlord. Access requires owner approval.':
          'سجّل ملفك للوصول إلى الصيانة وسجل الدفع ومطالبات الإيجار ومراسلة المالك. يتطلب الدخول موافقة المالك.',
      'Your resident profile has been registered and is currently under review by the property landlord.\n\nOnce the landlord approves your access and links your profile to an apartment lease, you will be able to access the full features of the app.':
          'تم تسجيل ملفك وهو قيد مراجعة المالك.\n\nبعد الموافقة وربط ملفك بعقد إيجار ستتمكن من استخدام جميع خصائص التطبيق.',
      'Enter the email address associated with your account and we\'ll send you instructions to reset your password.':
          'أدخل البريد المرتبط بحسابك وسنرسل إليك تعليمات إعادة تعيين كلمة المرور.',
      'Cannot approve tenant: No vacant units available. Please create a building structure first!':
          'لا يمكن الموافقة: لا توجد وحدات شاغرة. أنشئ هيكل المبنى أولًا.',
      'Floor: {}': 'الطابق: {}',
      'Category: {}': 'الفئة: {}',
      'Unit: {}': 'الوحدة: {}',
      'Resolved: ': 'تم الحل: ',
      'Submitted: ': 'تم الإرسال: ',
      'Notification dispatched successfully!': 'تم إرسال الإشعار بنجاح!',
      'Monthly Rent Invoice': 'فاتورة الإيجار الشهري',
      'Standard monthly apartment unit rent.':
          'الإيجار الشهري المعتاد للوحدة السكنية.',
      'Hello, {}!': 'مرحبًا، {}!',
      'Approve & Assign: {}': 'موافقة وتعيين: {}',
      'Approved and assigned {} successfully!':
          'تمت الموافقة على {} وتعيينه بنجاح!',
      'We have sent password recovery instructions to {}.':
          'أرسلنا تعليمات استعادة كلمة المرور إلى {}.',
      'Broadcast message sent to {} apartments successfully!':
          'تم إرسال الرسالة إلى {} شقة بنجاح!',
      'REF: {}': 'المرجع: {}',
      'Paid via: {}': 'تم الدفع عبر: {}',
    },
  };
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'es', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture<AppLocalizations>(AppLocalizations(locale));

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
