import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const _localizedValues = {
    'en': {
      'app_name': 'SMS Services',
      'app_title': 'SMS SERVICES',
      'login_subtitle': 'Sign in to manage your property',
      'email': 'Email Address',
      'password': 'Password',
      'forgot_password': 'Forgot password?',
      'sign_in': 'Sign In',
      'remember_me': 'Remember me',
      'invalid_auth': 'Invalid email or password',
      'current_residence': 'Current Residence',
      'maintenance_request': 'Maintenance Request',
      'maintenance_request_desc': 'Report an issue or track an existing request.',
      'upcoming_balance': 'Upcoming Balance',
      'due_in_days': 'Due in {} days',
      'recent_notifications': 'Recent Notifications',
      'mark_all_read': 'Mark all as read',
      'view_all': 'View all',
      'home': 'Home',
      'maintenance': 'Maintenance',
      'payments': 'Send Data',
      'profile': 'Profile',
      'settings': 'Settings',
      'log_out': 'Log Out',
      'unit': 'Unit {}',
      'lease_expires': 'Lease expires {}',
      'maintenance_center': 'Maintenance Center',
      'maintenance_desc': 'Submit new requests or review your past maintenance history.',
      'new_request': 'New Request',
      'history': 'Maintenance History',
      'category': 'Issue Category',
      'plumbing': 'Plumbing',
      'electrical': 'Electrical',
      'appliance': 'Appliance',
      'other': 'Other',
      'full_name': 'Full Name',
      'preferred_date': 'Preferred Repair Date',
      'req_info': 'Request Information',
      'describe_issue': 'Describe the issue in detail...',
      'attach_photos': 'Attach Photos',
      'upload_photos': 'Upload Photos',
      'max_photos': 'Max 3 photos, JPG or PNG',
      'submit_request': 'Submit Request',
      'req_success': 'Request Submitted Successfully',
      'view_request': 'View Request',
      'back_to_home': 'Back to Home',
      'assigned_tech': 'Assigned Technician',
      'timeline': 'Timeline',
      'status': 'Status',
      'pending': 'Pending',
      'in_progress': 'In Progress',
      'scheduled': 'Scheduled',
      'closed': 'Closed',
      'cancelled': 'Cancelled',
      'manage_balance': 'Manage your balance and review submission history.',
      'current_balance': 'Current Balance',
      'past_due': 'Past Due',
      'due_by': 'Due by {}',
      'late_status': '{} days late',
      'charge_breakdown': 'Breakdown of Charges',
      'total_due': 'Total Amount Due',
      'receipt': 'Submission Details',
      'txn_id': 'Transaction/Reference ID',
      'rent_period': 'Rent Period',
      'charges': 'Charges',
      'pay_method': 'Submission Method',
      'pay_date': 'Submission Date',
      'total': 'Total',
      'download_receipt': 'Download Receipt',
      'pay_now': 'Send Data',
      'confirm_payment': 'Confirm Submission',
      'payment_method_desc': 'Select your submission method, enter transaction reference details, and upload proof.',
      'select_payment_method': 'SELECT METHOD',
      'proof_of_payment': 'PROOF OF SUBMISSION',
      'attach_payment_receipt': 'Tap to Attach Receipt Proof (JPG, PNG, PDF)',
      'send_amount': 'Send {}',
      'submission_success': 'Data Submitted Successfully!',
      'submission_failed': 'Submission failed: {}',
      'balance_charges': 'Balance & Charges',
      'payment_history': 'Submission History',
      'submission_success_desc': 'Thank you. Your data has been submitted successfully for verification.',
      'view_transaction': 'View History',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'tomorrow': 'Tomorrow',
      'days_ago': '{} days ago',
      'in_days': 'In {} days',
      'due_today': 'Due Today',
      'insurance_coverage': 'Insurance Coverage',
      'insurance_desc': 'Manage your renter\'s insurance policy details and ensure continuous coverage for your unit.',
      'active_policy': 'Active Policy',
      'policy_no': 'Policy #',
      'coverage_amount': 'Coverage Amount',
      'deductible': 'Deductible',
      'effective_date': 'Effective Date',
      'expiration_date': 'Expiration Date',
      'view_pdf': 'View Full Policy PDF',
      'update_policy': 'Update Policy Information',
      'provider': 'Insurance Provider',
      'policy_number': 'Policy Number',
      'upload_proof': 'Upload Proof of Insurance',
      'save_updates': 'Save Updates',
      'lease_reqs': 'Lease Requirements',
      'min_coverage': 'Minimum \$50,000 liability coverage.',
      'mgmt_listed': 'Property Management Company must be listed as an "Interested Party".',
      'continuous_coverage': 'Continuous coverage required for the duration of the lease.',
      'insurance_warning': 'Failure to maintain active insurance may result in a non-compliance fee.',
      'lang_label': 'Language',
      'push_notif': 'Push Notifications',
      'email_notif': 'Email Notifications',
      'pay_notif': 'Payment Notifications',
      'maint_notif': 'Maintenance Notifications',
      'ins_alert': 'Insurance Alerts',
      'dark_mode': 'Dark Mode',
      'change_pw': 'Change Password',
      'privacy_policy': 'Privacy Policy',
      'terms': 'Terms & Conditions',
      'about': 'About SMS Services',
      'upload_success': 'File Uploaded Successfully',
      'error_loading': 'Unable to load content',
      'try_again': 'Try Again',
      'no_internet': 'No Internet Connection',
      'session_expired': 'Session Expired',
      'all': 'All',
      'unread': 'Unread',
      'general': 'General',
      'edit_profile': 'Edit Profile',
      'phone_number': 'Phone Number',
      'emergency_contact': 'Emergency Contact',
      'save_changes': 'Save Changes',
      'lease_start': 'Lease Start Date',
    },
    'es': {
      'app_name': 'SMS Services',
      'app_title': 'SMS SERVICES',
      'login_subtitle': 'Inicie sesión para administrar su propiedad',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'forgot_password': '¿Olvidó su contraseña?',
      'sign_in': 'Iniciar sesión',
      'remember_me': 'Recordarme',
      'invalid_auth': 'Correo electrónico o contraseña incorrectos',
      'current_residence': 'Residencia actual',
      'maintenance_request': 'Solicitud de mantenimiento',
      'maintenance_request_desc': 'Reportar un problema o realizar seguimiento.',
      'upcoming_balance': 'Saldo pendiente',
      'due_in_days': 'Vence en {} días',
      'recent_notifications': 'Notificaciones recientes',
      'mark_all_read': 'Marcar todo como leído',
      'view_all': 'Ver todo',
      'home': 'Inicio',
      'maintenance': 'Mantenimiento',
      'payments': 'Enviar datos',
      'profile': 'Perfil',
      'settings': 'Ajustes',
      'log_out': 'Cerrar sesión',
      'unit': 'Unidad {}',
      'lease_expires': 'El contrato vence el {}',
      'maintenance_center': 'Centro de mantenimiento',
      'maintenance_desc': 'Envíe nuevas solicitudes o revise su historial.',
      'new_request': 'Nueva solicitud',
      'history': 'Historial de mantenimiento',
      'category': 'Categoría del problema',
      'plumbing': 'Plomería',
      'electrical': 'Electricidad',
      'appliance': 'Electrodoméstico',
      'other': 'Otro',
      'full_name': 'Nombre completo',
      'preferred_date': 'Fecha preferida de reparación',
      'req_info': 'Información de solicitud',
      'describe_issue': 'Describa el problema en detalle...',
      'attach_photos': 'Adjuntar fotos',
      'upload_photos': 'Subir fotos',
      'max_photos': 'Máximo 3 fotos, JPG o PNG',
      'submit_request': 'Enviar solicitud',
      'req_success': 'Solicitud enviada con éxito',
      'view_request': 'Ver solicitud',
      'back_to_home': 'Volver al inicio',
      'assigned_tech': 'Técnico asignado',
      'timeline': 'Línea de tiempo',
      'status': 'Estado',
      'pending': 'Pendiente',
      'in_progress': 'En progreso',
      'scheduled': 'Programado',
      'closed': 'Cerrado',
      'cancelled': 'Cancelado',
      'manage_balance': 'Administre su saldo e historial de envíos.',
      'current_balance': 'Saldo actual',
      'past_due': 'Vencido',
      'due_by': 'Vence el {}',
      'late_status': '{} días de retraso',
      'charge_breakdown': 'Desglose de cargos',
      'total_due': 'Total a pagar',
      'receipt': 'Detalles del envío',
      'txn_id': 'ID de transacción/referencia',
      'rent_period': 'Período de renta',
      'charges': 'Cargos',
      'pay_method': 'Método de envío',
      'pay_date': 'Fecha de envío',
      'total': 'Total',
      'download_receipt': 'Descargar recibo',
      'pay_now': 'Enviar datos',
      'confirm_payment': 'Confirmar envío',
      'payment_method_desc': 'Seleccione el método de envío, ingrese los detalles de referencia de la transacción y cargue el comprobante.',
      'select_payment_method': 'SELECCIONAR MÉTODO',
      'proof_of_payment': 'COMPROBANTE DE ENVÍO',
      'attach_payment_receipt': 'Toque para adjuntar comprobante (JPG, PNG, PDF)',
      'send_amount': 'Enviar {}',
      'submission_success': '¡Datos enviados con éxito!',
      'submission_failed': 'El envío falló: {}',
      'balance_charges': 'Saldo y cargos',
      'payment_history': 'Historial de envíos',
      'submission_success_desc': 'Gracias. Sus datos han sido enviados con éxito para verificación.',
      'view_transaction': 'Ver historial',
      'today': 'Hoy',
      'yesterday': 'Ayer',
      'tomorrow': 'Mañana',
      'days_ago': 'hace {} días',
      'in_days': 'En {} días',
      'due_today': 'Vence hoy',
      'insurance_coverage': 'Cobertura de seguro',
      'insurance_desc': 'Administre los detalles de su póliza de seguro de inquilino.',
      'active_policy': 'Póliza activa',
      'policy_no': 'Nº de póliza',
      'coverage_amount': 'Monto de cobertura',
      'deductible': 'Deducible',
      'effective_date': 'Fecha de vigencia',
      'expiration_date': 'Fecha de vencimiento',
      'view_pdf': 'Ver PDF completo de la póliza',
      'update_policy': 'Actualizar información de póliza',
      'provider': 'Proveedor de seguro',
      'policy_number': 'Número de póliza',
      'upload_proof': 'Subir comprobante de seguro',
      'save_updates': 'Guardar actualizaciones',
      'lease_reqs': 'Requisitos del contrato',
      'min_coverage': 'Cobertura mínima de responsabilidad de \$50,000.',
      'mgmt_listed': 'La empresa de administración debe figurar como "Parte interesada".',
      'continuous_coverage': 'Se requiere cobertura continua durante el contrato.',
      'insurance_warning': 'El incumplimiento del seguro puede resultar en cargos adicionales.',
      'lang_label': 'Idioma',
      'push_notif': 'Notificaciones push',
      'email_notif': 'Notificaciones por correo',
      'pay_notif': 'Notificaciones de pago',
      'maint_notif': 'Notificaciones de mantenimiento',
      'ins_alert': 'Alertas de seguro',
      'dark_mode': 'Modo oscuro',
      'change_pw': 'Cambiar contraseña',
      'privacy_policy': 'Política de privacidad',
      'terms': 'Términos y condiciones',
      'about': 'Acerca de SMS Services',
      'upload_success': 'Archivo subido con éxito',
      'error_loading': 'No se pudo cargar el contenido',
      'try_again': 'Intentar de nuevo',
      'no_internet': 'Sin conexión a internet',
      'session_expired': 'Sesión expirada',
      'all': 'Todo',
      'unread': 'No leído',
      'general': 'General',
      'edit_profile': 'Editar perfil',
      'phone_number': 'Número de teléfono',
      'emergency_contact': 'Contacto de emergencia',
      'save_changes': 'Guardar cambios',
      'lease_start': 'Inicio de contrato',
    },
    'ar': {
      'app_name': 'خدمات SMS',
      'app_title': 'خدمات SMS',
      'login_subtitle': 'سجل دخولك لإدارة وحدتك السكنية',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'sign_in': 'تسجيل الدخول',
      'remember_me': 'تذكرني',
      'invalid_auth': 'البريد الإلكتروني أو كلمة المرور غير صالحة',
      'current_residence': 'السكن الحالي',
      'maintenance_request': 'طلب صيانة',
      'maintenance_request_desc': 'الإبلاغ عن مشكلة أو تتبع طلب قائم.',
      'upcoming_balance': 'المستحقات القادمة',
      'due_in_days': 'يستحق خلال {} أيام',
      'recent_notifications': 'آخر الإشعارات',
      'mark_all_read': 'تحديد الكل كمقروء',
      'view_all': 'عرض الكل',
      'home': 'الرئيسية',
      'maintenance': 'الصيانة',
      'payments': 'إرسال البيانات',
      'profile': 'الملف الشخصي',
      'settings': 'الإعدادات',
      'log_out': 'تسجيل الخروج',
      'unit': 'شقة {}',
      'lease_expires': 'ينتهي العقد في {}',
      'maintenance_center': 'مركز الصيانة',
      'maintenance_desc': 'إرسال طلب جديد أو مراجعة سجل طلبات الصيانة السابقة.',
      'new_request': 'طلب جديد',
      'history': 'سجل الصيانة',
      'category': 'فئة المشكلة',
      'plumbing': 'سباكة',
      'electrical': 'كهرباء',
      'appliance': 'أجهزة منزلية',
      'other': 'أخرى',
      'full_name': 'الاسم بالكامل',
      'preferred_date': 'موعد الإصلاح المفضل',
      'req_info': 'معلومات الطلب',
      'describe_issue': 'يرجى وصف المشكلة بالتفصيل...',
      'attach_photos': 'إرفاق صور',
      'upload_photos': 'تحميل الصور',
      'max_photos': 'الحد الأقصى 3 صور، بصيغة JPG أو PNG',
      'submit_request': 'إرسال الطلب',
      'req_success': 'تم إرسال الطلب بنجاح',
      'view_request': 'عرض الطلب',
      'back_to_home': 'العودة للرئيسية',
      'assigned_tech': 'الفني المعين',
      'timeline': 'الخط الزمني',
      'status': 'الحالة',
      'pending': 'قيد الانتظار',
      'in_progress': 'قيد العمل',
      'scheduled': 'مجدول',
      'closed': 'مغلق',
      'cancelled': 'ملغى',
      'manage_balance': 'إدارة الرصيد ومراجعة سجل إرسال البيانات.',
      'current_balance': 'الرصيد الحالي',
      'past_due': 'متأخرات',
      'due_by': 'يستحق في {}',
      'late_status': 'متأخر منذ {} أيام',
      'charge_breakdown': 'تفاصيل المستحقات',
      'total_due': 'إجمالي المبلغ المطلوب',
      'receipt': 'تفاصيل الإرسال',
      'txn_id': 'معرف المعاملة/المرجع',
      'rent_period': 'فترة الإيجار',
      'charges': 'الرسوم والمستحقات',
      'pay_method': 'طريقة الإرسال',
      'pay_date': 'تاريخ الإرسال',
      'total': 'الإجمالي',
      'download_receipt': 'تحميل إيصال الإرسال',
      'pay_now': 'إرسال البيانات',
      'confirm_payment': 'تأكيد إرسال البيانات',
      'payment_method_desc': 'اختر طريقة الإرسال، واكتب تفاصيل الحوالة/المرجع، ثم أرفق صورة الإثبات.',
      'select_payment_method': 'طريقة الإرسال',
      'proof_of_payment': 'إثبات الإرسال',
      'attach_payment_receipt': 'انقر لإرفاق صورة الإثبات (JPG, PNG, PDF)',
      'send_amount': 'إرسال {}',
      'submission_success': 'تم إرسال البيانات بنجاح!',
      'submission_failed': 'فشل الإرسال: {}',
      'balance_charges': 'الرصيد والمستحقات',
      'payment_history': 'سجل الإرسال',
      'submission_success_desc': 'شكرًا لك. تم إرسال البيانات بنجاح وجاري التحقق منها.',
      'view_transaction': 'عرض السجل',
      'today': 'اليوم',
      'yesterday': 'أمس',
      'tomorrow': 'غداً',
      'days_ago': 'منذ {} أيام',
      'in_days': 'خلال {} أيام',
      'due_today': 'يستحق اليوم',
      'insurance_coverage': 'التغطية التأمينية',
      'insurance_desc': 'إدارة تفاصيل وثيقة تأمين المستأجر وضمان التغطية المستمرة لوحدتك.',
      'active_policy': 'وثيقة تأمين نشطة',
      'policy_no': 'رقم الوثيقة',
      'coverage_amount': 'مبلغ التغطية',
      'deductible': 'مبلغ التحمل',
      'effective_date': 'تاريخ السريان',
      'expiration_date': 'تاريخ الانتهاء',
      'view_pdf': 'عرض ملف الوثيقة بالكامل PDF',
      'update_policy': 'تحديث بيانات التأمين',
      'provider': 'شركة التأمين',
      'policy_number': 'رقم وثيقة التأمين',
      'upload_proof': 'تحميل إثبات التأمين',
      'save_updates': 'حفظ التحديثات',
      'lease_reqs': 'شروط العقد',
      'min_coverage': 'الحد الأدنى للتغطية ضد المسؤولية 50,000 دولار.',
      'mgmt_listed': 'يجب إدراج شركة إدارة العقارات كـ "طرف مهتم".',
      'continuous_coverage': 'التغطية التأمينية المستمرة مطلوبة طوال مدة الإيجار.',
      'insurance_warning': 'قد يؤدي عدم الحفاظ على تأمين نشط إلى فرض رسوم مخالفة.',
      'lang_label': 'اللغة',
      'push_notif': 'الإشعارات الفورية',
      'email_notif': 'إشعارات البريد الإلكتروني',
      'pay_notif': 'إشعارات الدفع',
      'maint_notif': 'إشعارات الصيانة',
      'ins_alert': 'تنبيهات التأمين',
      'dark_mode': 'المظهر الداكن',
      'change_pw': 'تغيير كلمة المرور',
      'privacy_policy': 'سياسة الخصوصية',
      'terms': 'الشروط والأحكام',
      'about': 'حول خدمات SMS',
      'upload_success': 'تم تحميل الملف بنجاح',
      'error_loading': 'تعذر تحميل المحتوى',
      'try_again': 'إعادة المحاولة',
      'no_internet': 'لا يوجد اتصال بالإنترنت',
      'session_expired': 'انتهت صلاحية الجلسة',
      'all': 'الكل',
      'unread': 'غير مقروء',
      'general': 'عام',
      'edit_profile': 'تعديل الملف الشخصي',
      'phone_number': 'رقم الهاتف',
      'emergency_contact': 'جهة الاتصال في الطوارئ',
      'save_changes': 'حفظ التغييرات',
      'lease_start': 'بداية العقد',
    }
  };

  String translate(String key, [String? arg]) {
    final lang = locale.languageCode;
    String value = _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
    if (arg != null) {
      value = value.replaceFirst('{}', arg);
    }
    return value;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'es', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture<AppLocalizations>(AppLocalizations(locale));

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
