import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const _localizedValues = {
    'en': {
      'app_title': 'SMS SERVICES',
      'login_subtitle': 'Sign in to manage your property',
      'email': 'Email Address',
      'password': 'Password',
      'forgot_password': 'Forgot password?',
      'sign_in': 'Sign In',
      'remember_me': 'Remember me',
      'invalid_auth': 'Invalid email or password',
      'current_residence': 'Current Residence',
      'maintenance_request': 'Maintenance Request',
      'maintenance_request_desc': 'Report an issue or track an existing request.',
      'upcoming_balance': 'Upcoming Balance',
      'due_in_days': 'Due in {} days',
      'recent_notifications': 'Recent Notifications',
      'mark_all_read': 'Mark all as read',
      'view_all': 'View all',
      'home': 'Home',
      'maintenance': 'Maintenance',
      'payments': 'Payments',
      'profile': 'Profile',
      'settings': 'Settings',
      'log_out': 'Log Out',
      'unit': 'Unit {}',
      'lease_expires': 'Lease expires {}',
      'maintenance_center': 'Maintenance Center',
      'maintenance_desc': 'Submit new requests or review your past maintenance history.',
      'new_request': 'New Request',
      'history': 'Maintenance History',
      'category': 'Issue Category',
      'plumbing': 'Plumbing',
      'electrical': 'Electrical',
      'appliance': 'Appliance',
      'other': 'Other',
      'full_name': 'Full Name',
      'preferred_date': 'Preferred Repair Date',
      'req_info': 'Request Information',
      'describe_issue': 'Describe the issue in detail...',
      'attach_photos': 'Attach Photos',
      'upload_photos': 'Upload Photos',
      'max_photos': 'Max 3 photos, JPG or PNG',
      'submit_request': 'Submit Request',
      'req_success': 'Request Submitted Successfully',
      'view_request': 'View Request',
      'back_to_home': 'Back to Home',
      'assigned_tech': 'Assigned Technician',
      'timeline': 'Timeline',
      'status': 'Status',
      'pending': 'Pending',
      'in_progress': 'In Progress',
      'scheduled': 'Scheduled',
      'closed': 'Closed',
      'cancelled': 'Cancelled',
      'manage_balance': 'Manage your balance and review payment history.',
      'current_balance': 'Current Balance',
      'past_due': 'Past Due',
      'due_by': 'Due by {}',
      'late_status': '{} days late',
      'charge_breakdown': 'Breakdown of Charges',
      'total_due': 'Total Amount Due',
      'receipt': 'Receipt',
      'txn_id': 'Transaction ID',
      'rent_period': 'Rent Period',
      'charges': 'Charges',
      'pay_method': 'Payment Method',
      'pay_date': 'Payment Date',
      'total': 'Total',
      'download_receipt': 'Download Receipt',
      'pay_now': 'Pay Now',
      'insurance_coverage': 'Insurance Coverage',
      'insurance_desc': 'Manage your renter\'s insurance policy details and ensure continuous coverage for your unit.',
      'active_policy': 'Active Policy',
      'policy_no': 'Policy #',
      'coverage_amount': 'Coverage Amount',
      'deductible': 'Deductible',
      'effective_date': 'Effective Date',
      'expiration_date': 'Expiration Date',
      'view_pdf': 'View Full Policy PDF',
      'update_policy': 'Update Policy Information',
      'provider': 'Insurance Provider',
      'policy_number': 'Policy Number',
      'upload_proof': 'Upload Proof of Insurance',
      'save_updates': 'Save Updates',
      'lease_reqs': 'Lease Requirements',
      'min_coverage': 'Minimum \$50,000 liability coverage.',
      'mgmt_listed': 'Property Management Company must be listed as an "Interested Party".',
      'continuous_coverage': 'Continuous coverage required for the duration of the lease.',
      'insurance_warning': 'Failure to maintain active insurance may result in a non-compliance fee.',
      'lang_label': 'Language',
      'push_notif': 'Push Notifications',
      'email_notif': 'Email Notifications',
      'pay_notif': 'Payment Notifications',
      'maint_notif': 'Maintenance Notifications',
      'ins_alert': 'Insurance Alerts',
      'dark_mode': 'Dark Mode',
      'change_pw': 'Change Password',
      'privacy_policy': 'Privacy Policy',
      'terms': 'Terms & Conditions',
      'about': 'About SMS Services',
      'upload_success': 'File Uploaded Successfully',
      'error_loading': 'Unable to load content',
      'try_again': 'Try Again',
      'no_internet': 'No Internet Connection',
      'session_expired': 'Session Expired',
      'all': 'All',
      'unread': 'Unread',
      'general': 'General',
      'edit_profile': 'Edit Profile',
      'phone_number': 'Phone Number',
      'emergency_contact': 'Emergency Contact',
      'save_changes': 'Save Changes',
      'lease_start': 'Lease Start Date',
    },
    'es': {
      'app_title': 'SMS SERVICES',
      'login_subtitle': 'Inicie sesión para administrar su propiedad',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'forgot_password': '¿Olvidó su contraseña?',
      'sign_in': 'Iniciar sesión',
      'remember_me': 'Recordarme',
      'invalid_auth': 'Correo electrónico o contraseña incorrectos',
      'current_residence': 'Residencia actual',
      'maintenance_request': 'Solicitud de mantenimiento',
      'maintenance_request_desc': 'Reportar un problema o realizar seguimiento.',
      'upcoming_balance': 'Saldo pendiente',
      'due_in_days': 'Vence en {} días',
      'recent_notifications': 'Notificaciones recientes',
      'mark_all_read': 'Marcar todo como leído',
      'view_all': 'Ver todo',
      'home': 'Inicio',
      'maintenance': 'Mantenimiento',
      'payments': 'Pagos',
      'profile': 'Perfil',
      'settings': 'Ajustes',
      'log_out': 'Cerrar sesión',
      'unit': 'Unidad {}',
      'lease_expires': 'El contrato vence el {}',
      'maintenance_center': 'Centro de mantenimiento',
      'maintenance_desc': 'Envíe nuevas solicitudes o revise su historial.',
      'new_request': 'Nueva solicitud',
      'history': 'Historial de mantenimiento',
      'category': 'Categoría del problema',
      'plumbing': 'Plomería',
      'electrical': 'Electricidad',
      'appliance': 'Electrodoméstico',
      'other': 'Otro',
      'full_name': 'Nombre completo',
      'preferred_date': 'Fecha preferida de reparación',
      'req_info': 'Información de solicitud',
      'describe_issue': 'Describa el problema en detalle...',
      'attach_photos': 'Adjuntar fotos',
      'upload_photos': 'Subir fotos',
      'max_photos': 'Máximo 3 fotos, JPG o PNG',
      'submit_request': 'Enviar solicitud',
      'req_success': 'Solicitud enviada con éxito',
      'view_request': 'Ver solicitud',
      'back_to_home': 'Volver al inicio',
      'assigned_tech': 'Técnico asignado',
      'timeline': 'Línea de tiempo',
      'status': 'Estado',
      'pending': 'Pendiente',
      'in_progress': 'En progreso',
      'scheduled': 'Programado',
      'closed': 'Cerrado',
      'cancelled': 'Cancelado',
      'manage_balance': 'Administre su saldo e historial de pagos.',
      'current_balance': 'Saldo actual',
      'past_due': 'Vencido',
      'due_by': 'Vence el {}',
      'late_status': '{} días de retraso',
      'charge_breakdown': 'Desglose de cargos',
      'total_due': 'Total a pagar',
      'receipt': 'Recibo',
      'txn_id': 'ID de transacción',
      'rent_period': 'Período de renta',
      'charges': 'Cargos',
      'pay_method': 'Método de pago',
      'pay_date': 'Fecha de pago',
      'total': 'Total',
      'download_receipt': 'Descargar recibo',
      'pay_now': 'Pagar ahora',
      'insurance_coverage': 'Cobertura de seguro',
      'insurance_desc': 'Administre los detalles de su póliza de seguro de inquilino.',
      'active_policy': 'Póliza activa',
      'policy_no': 'Nº de póliza',
      'coverage_amount': 'Monto de cobertura',
      'deductible': 'Deducible',
      'effective_date': 'Fecha de vigencia',
      'expiration_date': 'Fecha de vencimiento',
      'view_pdf': 'Ver PDF completo de la póliza',
      'update_policy': 'Actualizar información de póliza',
      'provider': 'Proveedor de seguro',
      'policy_number': 'Número de póliza',
      'upload_proof': 'Subir comprobante de seguro',
      'save_updates': 'Guardar actualizaciones',
      'lease_reqs': 'Requisitos del contrato',
      'min_coverage': 'Cobertura mínima de responsabilidad de \$50,000.',
      'mgmt_listed': 'La empresa de administración debe figurar como "Parte interesada".',
      'continuous_coverage': 'Se requiere cobertura continua durante el contrato.',
      'insurance_warning': 'El incumplimiento del seguro puede resultar en cargos adicionales.',
      'lang_label': 'Idioma',
      'push_notif': 'Notificaciones push',
      'email_notif': 'Notificaciones por correo',
      'pay_notif': 'Notificaciones de pago',
      'maint_notif': 'Notificaciones de mantenimiento',
      'ins_alert': 'Alertas de seguro',
      'dark_mode': 'Modo oscuro',
      'change_pw': 'Cambiar contraseña',
      'privacy_policy': 'Política de privacidad',
      'terms': 'Términos y condiciones',
      'about': 'Acerca de SMS Services',
      'upload_success': 'Archivo subido con éxito',
      'error_loading': 'No se pudo cargar el contenido',
      'try_again': 'Intentar de nuevo',
      'no_internet': 'Sin conexión a internet',
      'session_expired': 'Sesión expirada',
      'all': 'Todo',
      'unread': 'No leído',
      'general': 'General',
      'edit_profile': 'Editar perfil',
      'phone_number': 'Número de teléfono',
      'emergency_contact': 'Contacto de emergencia',
      'save_changes': 'Guardar cambios',
      'lease_start': 'Inicio de contrato',
    }
  };

  String translate(String key, [String? arg]) {
    final lang = locale.languageCode;
    String value = _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
    if (arg != null) {
      value = value.replaceFirst('{}', arg);
    }
    return value;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'es'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture<AppLocalizations>(AppLocalizations(locale));

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
